site_name: My Static Site
site_author: Budzinskaya Nina

repo_url: 

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  custom_dir: 'custom_theme/'



nav:
  - Главная: index.md
  - Резюме: cv.md
  - Отчёты:
    - Практика 1: 
    - Практика 2: 




    