site_name: My Static Site
site_author: Budzinskaya Nina

repo_url: https://github.com/nina440/my-static-site-python

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  custom_dir: 'custom_theme/'




    